name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Docker login for GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          IMAGE_NAME: king-for-kong
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}${{ github.repository_name }}
          TAG: latest
        run: |
          docker build -t $DOCKER_REPO/$IMAGE_NAME:$TAG .
          docker push $DOCKER_REPO/$IMAGE_NAME:$TAG
