name: Auto Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitVersion
        run: |
          wget https://github.com/GitTools/GitVersion/releases/latest/download/gitversion-linux-x64.tar.gz -O gitversion.tar.gz
          tar -xzf gitversion.tar.gz
          chmod +x ./gitversion

      - name: Analyze version
        id: analyze_version
        run: |
          ./gitversion /output buildserver /nofetch
          echo "VERSION=$(cat GitVersion.yml | yq r - -j | jq -r '.SemVer')" >> $GITHUB_ENV
      
      - name: Login to GitHub
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Create and push new tag
        run: |
          git tag $VERSION
          git push origin $VERSION
