name: Auto Tagging

on:
  push:
    branches:
      - main

jobs:
  tag:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: echo "::set-env name=LATEST_TAG::$(git describe --tags --abbrev=0)"

      - name: Install semver package
        run: npm install --global semver
      
      - name: Generate new tag
        id: new_tag
        run: echo "::set-env name=NEW_TAG::$(semver --increment patch ${{ env.LATEST_TAG }})"

      - name: Login to GitHub
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Create and push new tag
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
